### PR TITLE
Fix #11

### LINKED ISSUE #11: AttributeError: 'str' object has no attribute 'decode'
Same issue that:
adafruit/Adafruit_CircuitPython_Thermal_Printer#9
https://github.com/adafruit/Adafruit_CircuitPython_binascii/issues/6

The problem is for SAMD21 non-express boards only.

### PR DESCRIPTION
**Pull request by fgallaire**

### CODE REVIEW

**Comment by fgallaire** [comment]
@brentru ?

**Comment by kattni** [comment]
@brentru Please take a look at this when you get a chance. Thank you.

**Comment by brentru** [comment]
@kattni  Will test on an itsy m0 by EOD.

**Review by brentru — APPROVED** [review]
LGTM!

**Pull request merged**
