### PR TITLE
Add binascii lib in requirements

### PR DESCRIPTION
**Pull request by fgallaire**

### CODE REVIEW

**Comment by brentru** [comment]
@fgallaire  Thanks, just checked to see if we were missing anything else and now it looks good.

**Comment by brentru** [comment]
@fgallaire  Thanks!  just checked to see if we were missing anything else, LGTM!

**Comment by tannewt** [comment]
Why is this needed? `binascii` is provided by CPython

**Comment by fgallaire** [comment]
hello @tannewt ISTM it's the best way to do it:
- no import code to change between CPU and MCU versions
- not relying on two differents libs so no compatibility bug surprises

**Comment by tannewt** [comment]
For 1) we should fix the binascii CircuitPython library to use the same name and 2) ensure they are compatible. There is no reason to have two similar but not compatible things.

@brentru can you take this on?

**Comment by fgallaire** [comment]
@tannewt what you propose is
1) more work to make it work
2) more risk to make it fail

Is this really necessary as using CircuitPython_binascii just is not a problem ?

**Comment by tannewt** [comment]
While it may be more work now, it isn't more work over the long term. Maintaining two flavors of something is a long term cost.

**Pull request closed without merging**
